// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDORmCE3_nkvWSWbabtrRcE1kLegEmwyWs',
    appId: '1:538186647136:web:d11aa83fad67889c3e2505',
    messagingSenderId: '538186647136',
    projectId: 'urbanharmonygdnu',
    authDomain: 'urbanharmonygdnu.firebaseapp.com',
    databaseURL: 'https://urbanharmonygdnu-default-rtdb.firebaseio.com',
    storageBucket: 'urbanharmonygdnu.appspot.com',
    measurementId: 'G-FKL4WD751T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6z-lp_j4UNVJ7siBoIGTzTEffjq5QK9c',
    appId: '1:538186647136:android:be6c7c6e04adc2543e2505',
    messagingSenderId: '538186647136',
    projectId: 'urbanharmonygdnu',
    databaseURL: 'https://urbanharmonygdnu-default-rtdb.firebaseio.com',
    storageBucket: 'urbanharmonygdnu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoqxS7R8rpA5LlMWKY6pxT91K1lhvY8lc',
    appId: '1:538186647136:ios:d9c1df8552de736e3e2505',
    messagingSenderId: '538186647136',
    projectId: 'urbanharmonygdnu',
    databaseURL: 'https://urbanharmonygdnu-default-rtdb.firebaseio.com',
    storageBucket: 'urbanharmonygdnu.appspot.com',
    iosBundleId: 'com.example.flutterProject2208e',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoqxS7R8rpA5LlMWKY6pxT91K1lhvY8lc',
    appId: '1:538186647136:ios:d9c1df8552de736e3e2505',
    messagingSenderId: '538186647136',
    projectId: 'urbanharmonygdnu',
    databaseURL: 'https://urbanharmonygdnu-default-rtdb.firebaseio.com',
    storageBucket: 'urbanharmonygdnu.appspot.com',
    iosBundleId: 'com.example.flutterProject2208e',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDORmCE3_nkvWSWbabtrRcE1kLegEmwyWs',
    appId: '1:538186647136:web:90e0d9437be445de3e2505',
    messagingSenderId: '538186647136',
    projectId: 'urbanharmonygdnu',
    authDomain: 'urbanharmonygdnu.firebaseapp.com',
    databaseURL: 'https://urbanharmonygdnu-default-rtdb.firebaseio.com',
    storageBucket: 'urbanharmonygdnu.appspot.com',
    measurementId: 'G-W8VHWBL5EE',
  );

}