import 'package:flutter_project_2208e/Admin/addGalleryPicture.dart';
import 'package:flutter_project_2208e/Admin/addProduct.dart';
import 'package:flutter_project_2208e/Admin/adminpage.dart';
import 'package:flutter_project_2208e/Admin/galleryReviews.dart';
import 'package:flutter_project_2208e/Admin/manageuser.dart';
import 'package:flutter_project_2208e/Admin/review_product.dart';
import 'package:flutter_project_2208e/Admin/view_manageGallery_design.dart';
import 'package:flutter_project_2208e/Admin/view_products.dart';
import 'package:flutter_project_2208e/Consultant/addConsultationTime.dart';
import 'package:flutter_project_2208e/Consultant/add_project.dart';
import 'package:flutter_project_2208e/Consultant/consultant.dart';
import 'package:flutter_project_2208e/Consultant/create_professional_details.dart';
import 'package:flutter_project_2208e/Consultant/reviewsSection.dart';
import 'package:flutter_project_2208e/Consultant/viewConsulatations.dart';
import 'package:flutter_project_2208e/Consultant/view_personal_details.dart';
import 'package:flutter_project_2208e/Consultant/view_professionalDetails.dart';
import 'package:flutter_project_2208e/Consultant/view_projects.dart';
import 'package:flutter_project_2208e/screens/Contact_Us.dart';
import 'package:flutter_project_2208e/screens/MyDesigns.dart';
import 'package:flutter_project_2208e/screens/about_page.dart';
import 'package:flutter_project_2208e/screens/blog.dart';
import 'package:flutter_project_2208e/screens/cart_page.dart';
import 'package:flutter_project_2208e/screens/categories/Curtains.dart';
import 'package:flutter_project_2208e/screens/home_page.dart';
import 'package:flutter_project_2208e/screens/login_page.dart';
import 'package:flutter_project_2208e/screens/manage_user_page.dart';
import 'package:flutter_project_2208e/screens/order_page.dart';
import 'package:flutter_project_2208e/screens/product_view_page.dart';
import 'package:flutter_project_2208e/screens/show_consultaion_timing.dart';
import 'package:flutter_project_2208e/screens/show_designers.dart';
import 'package:flutter_project_2208e/screens/show_saved_items.dart';
import 'package:flutter_project_2208e/screens/sitemap.dart';
import 'package:flutter_project_2208e/screens/view_Gallery.dart';

class PageRoutes{
  static const String home = HomePage.routeName;
  static const String about = AboutUsPage.routeName;
  static const String muser = ManageUserPage.routeName;
  static const String prodview = ProductViewPage.routeName;
  static const String cart = CartPage.routeName;
  static const String order = OrderPage.routeName;
  static const String admin = ManageAdminPage.routeName;
  static const String consultant = ManageConsultantPage.routeName;
  static const String prodAdd = AddDesigns.routeName;
  static const String prodDisp = DisplayProducts.routeName;
  static const String manageUser = UserManagementPage.routeName;
  static const String createProfCons = create_profileConsultant.routeName;
  static const String viewProfCons = ViewProfessionaldetails.routeName;
  static const String viewPersCons = ViewPersonaldetailsConsultant.routeName;
  static const String addProjCons = create_projectConsultant.routeName;
  static const String viewProjCons = ViewProjects.routeName;
  static const String addConsulTime = SetConsultationAvailabilityPage.routeName;
  static const String viewConsulTime = ViewConsultationsPage.routeName;
  static const String showDesignU = DesignersSection.routeName;
  static const String lognPage = LoginPage.routeName;
  static const String savedItems = viewSavedItems.routeName;
  static const String contactUs = ContactUsPage.routeName;
  static const String sitemap = SitemapPage.routeName;
  static const String view_consultant_user = ViewConsultationsUserPage.routeName;
  static const String reviewConultant = ReviewsSectionConsultant.routeName;
  static const String addGallery = addGalleryPicture.routeName;
  static const String viewDesign = ViewManagegalleryDesign.routeName;
  static const String reviewProductAdmin = ReviewProductAdmin.routeName;
  static const String galleryPage = GalleryPage.routeName;
  static const String myDesigns = MyDesigns.routeName;
  static const String gallery_reviewsAdmin = ReviewGalleryAdmin.routeName;
  static const String blogPage = BlogPage.routeName;

}